version: 0
metadata:
  name: Releasetasks Task Graph
  description: Releasetasks
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 1200
      image: "quay.io/mrrrgn/ubuntu-ci:0.0.2"
      command:
        - "/bin/bash"
        - "-c"
        - "git clone $GITHUB_HEAD_REPO_URL && cd releasetasks && git checkout $GITHUB_HEAD_BRANCH && tox -e py27"
    extra:
      github:
        env: true
        events:
          - push
          - pull_request.*
    metadata:
      name: Releasetasks Pull Request
      description: Pull Request
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
